nelmio_api_doc:
    documentation:
        info:
            title: Event API
            description: API documentation for event endpoints
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/events
